name: Tests
on: [push]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build project
      run: |
        composer install --prefer-dist
        export APP_ENV=test
        php artisan key:generate --env=test
        env
        cat .env.test

    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        user: 'github'
        pass: 'secret'

    - run: mysql -uroot -h127.0.0.1 -e 'SELECT version()'
    - run: mysql -uroot -h127.0.0.1 -e 'CREATE DATABASE laravel'

    - run: php artisan migrate -n --force --env=test

    - name: Run PHPUnit
      run: |
        php vendor/bin/phpunit tests/Unit/*
