name: Tests
on: [push]

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build project
      run: |
        composer install --prefer-dist
        cp .env.example .env
        php artisan key:generate
        php artisan migrate
    - name: Run PHPUnit
      run: |
        php vendor/bin/phpunit